detect.output.path: /Users/shanty/blackduck/scan-outputs
blackduck.trust.cert: true
detect.accuracy.required: NONE

# Different CA than the rest
#blackduck.url: https://us03-qa-perf01.nprd.sig.synopsys.com
#blackduck.api.token: M2RlOTlhMTItNDcwYS00ODZlLWFkOGYtN2I2NmFlYmM4ODRjOjlhODZhMTQ1LWY2ZDUtNDBhNy05NWE2LTA1ZjJkN2MyMGRjYw==

# 2024.10.0
#blackduck.url: https://us03-qa-hub28.nprd.sig.synopsys.com // woooorrrkkks
#blackduck.api.token: ZWFiM2IyN2MtYWQyNC00N2EyLWIyNTItZDg5ZGMwMjAxMTM5OjNiMWVjNjUzLWYzMzktNDIwZi1iZWZkLWIyN2ZmMTUzYzlhMw==

# 2024.4.0
#blackduck.url: https://us03-sup-docker02-shankarm.nprd.sig.synopsys.com
#blackduck.api.token: YzA3MjdlY2ItMGI1Mi00ZWIwLWJjOWItMWMzODA1OGY3OWMzOjVmNzAyMzEwLTRmMmQtNGJiZi04ODA0LTBlOWY2NjJiZWE2MA==
#blackduck.api.token: YzA3MjdlY2ItMGI1Mi00ZWIwLWJjOWItMWMzODA1OGY3OWMzOjVmNzAyMzEwLTRmMmQtNGJiZi04ODA0LTBlOWY2NjJiZWE2MA==

# 2024.4.1
#blackduck.url: https://us03-eng-hub-docker-valid04.nprd.sig.synopsys.com
#blackduck.api.token: NDg1NzQ2YmYtYmM1YS00NTQ1LWJkNzMtNzI4NzBkODEzMTE3OmI4NmQ5MGQyLTk1ZTUtNGE4OS1iMDg1LTAxYjllNTNiZDg3Mw==

# CI PIPELINES
#blackduck.url: https://aws-int-butler.eng.aws.internal/
#blackduck.api.token: ZTY5ZTBhZWItNjE1Yi00NjEzLTg0YWYtN2QwZDMyZjliZmZhOjZiODgxMGY3LTMxMzEtNDYzMi04N2U4LWU1NWRhYjc4YWZjNQ==

#blackduck.url: https://aws-eng-hub-docker-valid01.eng.aws.internal
#blackduck.api.token: MjM2OWJlNTEtZjdjNS00MDU2LWFjMDAtNDcxNWFkZDViY2I1OmM3MjYzY2Y3LWEzZjMtNGYxNy1iMmJjLWQ2YTM4ZTk1MWJkZA==

#blackduck.url: https://aws-eng-hub-docker-valid03.eng.aws.internal
#blackduck.api.token: YmNjMTEwNTMtZjE1Yi00OTYwLTkyYjItNDllNmNmYzQ1ZmY1OjkyZTI2MThhLWVmNGYtNGY5MC1hNWJhLWIwZGRiNWQ4YjYwNg==

## 2024.10.1
#blackduck.url: https://aws-eng-hub-docker-valid02.eng.aws.internal
#blackduck.api.token: MmI2ODQ3MGUtZDUzOC00N2I0LWExNDItMmNjYzM4Yjc4ZDZhOjBmY2MxNDYxLWQ5ODQtNGU1MS04N2Y3LTAwYjU1NmYxNWIwYQ==

# 2025.1.1 non-sysadmin user
#blackduck.url: https://10.230.198.65
#blackduck.api.token: MDI1MWZlM2MtM2VlYy00YTVhLThjOTUtODI3NjNjMWVhMzZiOmFlZjBmNmNjLTAwNjMtNDRjOS05Y2ZmLWUyMTg4YWE1Nzc0Mg==

# 2025.1.1
blackduck.url: https://aws-eng-hub-docker-valid04.eng.aws.internal
blackduck.api.token: NDY2N2Y3YmEtNGEzZi00N2JkLTg5NjktYWI4ZDNhMjc2OTk5OjUzMmYwMWJjLWYxNjUtNGVlOS1iMzM3LTU2NDkyZjMzODdlMg==

# CD PIPELINES
#blackduck.url: https://us03-int-relcandi.nprd.sig.synopsys.com
#blackduck.api.token: MTUyMDNmNWYtZTU2Zi00N2ZkLWJhNTctM2IxMTZkYmFmOGZlOjYzMmJiNTM4LTFiYTYtNGJjZS04OWM3LWU0YTA0ODBkYmI2Nw==

# 2025.1.0
#blackduck.url: https://aws-eng-hub-docker-valid04.eng.aws.internal
#blackduck.api.token: NDg1NzQ2YmYtYmM1YS00NTQ1LWJkNzMtNzI4NzBkODEzMTE3OmI4NmQ5MGQyLTk1ZTUtNGE4OS1iMDg1LTAxYjllNTNiZDg3Mw==

# 2023.1.2
#blackduck.url: https://us03-int-hub03.nprd.sig.synopsys.com
#SYS-ADMIN
#blackduck.api.token: YWZhMTdjYWEtYmIzZi00OWRiLTg1NWMtYjAxOGRmZTYyZjNkOjIxYmY2ZmJkLWRmZGYtNGNlNC1iNjI3LWRjOTZlOGVjNzFlMA==
#NON-SYS-ADMIN
#blackduck.api.token: ZmIwMTZjZGItZTUxZi00NDUxLTg1MDMtZjM1NTVkNDc1YzQ4OmZiNjFiNjc0LTQ2YWQtNDQ5Mi1iNmNlLTE0NGNmY2NkOWI5MA==

#     LOCAL
#blackduck.url: https://localhost
#blackduck.api.token: MTRlOTljZDItOTRiYy00MTYyLTkzNTEtZDBkZTNlOWIzYWI4OjQyYjNkNjFhLWY5YzYtNDA1Mi1hNDgyLWYxN2YyMTBkNzU4ZQ==

#detect.source.path: /Users/shanty/Desktop/10.1.0-debugging
#detect.source.path: /Users/shanty/Downloads/gradle-rich-versions-project
#detect.source.path: /Users/shanty/blackduck/example-source/npm/WebGoat
#detect.source.path: /Users/shanty/blackduck/example-source/nuget/dotnet
#detect.source.path: /Users/shanty/blackduck/example-source/maven/insecure-bank
#detect.source.path: /Users/shanty/Downloads/notification_gateway
#detect.source.path: /Users/shanty/blackduck/example-source/maven/clock_maven
#detect.source.path: /Users/shanty/blackduck/example-source/maven/packtpub-xtext-book-2nd-examples/org.example.hellomaven.parent
#detect.source.path: /Users/shanty/Downloads/alex_test_csproj_props
#detect.source.path: /Users/shanty/blackduck/github-folder/detect
#detect.source.path: /Users/shanty/blackduck/example-source/yarn/yarn
#detect.source.path: /Users/shanty/blackduck/example-source/nuget/testing-4573
#detect.source.path: /Users/shanty/blackduck/example-source/gradle/gradle-multi-proj
detect.source.path: /Users/shanty/blackduck/example-source/go/ToReferLatest/GoViperTest
#detect.source.path: /Users/shanty/blackduck/example-source/go/go-modules-example


#detect.blackduck.signature.scanner.paths: /Users/shanty/Downloads/TutorialFiles.zip


#detect.nuget.dependency.types.excluded: DEV
detect.project.name: testing-4602
detect.project.version.name: demo
#detect.yarn.ignore.workspaces: ALL

detect.go.path: /opt/homebrew/bin/go
#detect.risk.report.pdf: true
#detect.risk.report.pdf.path: /Users/shanty/blackduck/scan-outputs/risk-reports
#detect.gradle.root.only: true
#detect.gradle.configuration.types.excluded: UNRESOLVED
#detect.gradle.included.projects: common
#detect.gradle.included.project.paths: :detect
#detect.gradle.excluded.projects: sub
#detect.gradle.excluded.configurations: compileClasspath, testCompileClasspath
#detect.gradle.configuration.types.excluded: UNRESOLVED

#detect.project.version.update: true
#detect.project.clone.categories: CUSTOM_FIELD_DATA
logging.level.detect: DEBUG
detect.diagnostic: true
detect.cleanup: false


#detect.wait.for.results: true
#detect.t: CONTAINER_SCAN
#detect.container.scan.file.path: /Users/shanty/Downloads/detect-run-2025-02-16-12-01-35-137.zip
#detect.impact.analysis.enabled: true
#detect.project.version.license: "Apache License 2.0"
#detect.policy.check.fail.on.severities: BLOCKER


detect.tools: DETECTOR
#detect.blackduck.signature.scanner.snippet.matching: FULL_SNIPPET_MATCHING
#detect.container.scan.file.path: /Users/shanty/Downloads/grafana-tempo.tar
#detect.threatintel.scan.file.path: /Users/shanty/Downloads/yarn.tar
#detect.blackduck.signature.scanner.local.path: /Users/shanty/blackduck/tools/Black_Duck_Scan_Installation/scan.cli-2023.1.2
#detect.maven.build.command: -T 1C -e -X
#detect.tools.excluded: SIGNATURE_SCAN

#detect.docker.image: nokia_image:Dockerfile
  
#detect.docker.platform.top.layer.id: sha256:ada24e7d50a6def17895ae268b5d341f0c7c76fd51e157a9a20f7f36a9a740d2 #actual base layer (layer 1) --> no results.
#detect.docker.platform.top.layer.id: sha256:af7ed92504ae4c20128a0f01048d41d467fef5c795c38d0defdb998a187ed1d4 #wrong layer (layer 2) --> unexpected results.
#detect.docker.platform.top.layer.id: sha256:af7ed92504ae4c20128a0f01048d41d467fef5c795c38d0defdb998a187ed1d4

#detect.project.user.groups: mau-IALERT-3355


#detect.project.inspector.path: /Users/shanty/blackduck/scan-tools/project-inspector-macosx-v2021-9-10-rc1

#detect.tools: SIGNATURE_SCAN
#detect.blackduck.scan.mode: STATELESS
#detect.policy.check.fail.on.names: IDETECT-3989-Policy
#detect.policy.check.fail.on.names: p1


################################################################################
#detect.component.location.analysis.enabled: true

# OFFLINE PACKAGE MANAGER SCAN
#blackduck.offline.mode: true
#blackduck.offline.mode.force.bdio: true
###################################
# ONLINE RAPID/STATELESS SCAN
detect.blackduck.scan.mode: RAPID

#SNPS_INTERNAL_ARTIFACTORY=https://artifactory.internal.synopsys.com
# ReversingLabs registration = QA_Norby_Auto_hub_key



