package com.blackduck.integration.detectable.detectables.cargo.functional;

import java.io.IOException;
import java.nio.file.Paths;

import org.jetbrains.annotations.NotNull;
import org.junit.jupiter.api.Assertions;

import com.blackduck.integration.bdio.model.Forge;
import com.blackduck.integration.detectable.Detectable;
import com.blackduck.integration.detectable.DetectableEnvironment;
import com.blackduck.integration.detectable.detectables.cargo.CargoDetectableOptions;
import com.blackduck.integration.detectable.extraction.Extraction;
import com.blackduck.integration.detectable.functional.DetectableFunctionalTest;
import com.blackduck.integration.detectable.util.graph.NameVersionGraphAssert;
import com.blackduck.integration.detectable.detectable.util.EnumListFilter;

/**
 * Tests workspace inheritance syntax in Cargo workspaces.
 * Verifies that dependencies with .workspace = true in member crates correctly
 * resolve versions from the root [workspace.dependencies] section.
 */
public class CargoLockfileWorkspaceInheritanceTest extends DetectableFunctionalTest {

    public CargoLockfileWorkspaceInheritanceTest() throws IOException {
        super("cargo-workspace-inheritance");
    }

    @Override
    protected void setup() throws IOException {
        // Root Cargo.toml with workspace definitions
        addFile(
            Paths.get("Cargo.toml"),
            "[workspace]",
            "resolver = \"2\"",
            "members = [",
            "    \"crates/system-manager-engine\",",
            "    \"crates/system-manager\",",
            "]",
            "",
            "[workspace.package]",
            "version = \"1.0.0\"",
            "edition = \"2021\"",
            "",
            "[workspace.dependencies]",
            "anyhow = \"1.0.68\"",
            "clap = \"4.1.4\"",
            "log = \"0.4.17\"",
            "serde = \"1.0.152\"",
            "system-manager-engine = { path = \"crates/system-manager-engine\" }",
            "",
            "[workspace.dev-dependencies]",
            "tokio = \"1.35.0\"",
            "",
            "[workspace.build-dependencies]",
            "cc = \"1.0.79\""
        );

        // system-manager workspace member
        addFile(
            Paths.get("crates/system-manager/Cargo.toml"),
            "[package]",
            "name = \"system-manager\"",
            "version.workspace = true",
            "edition.workspace = true",
            "",
            "[dependencies]",
            "system-manager-engine.workspace = true",
            "anyhow.workspace = true",
            "clap.workspace = true"
        );

        // system-manager-engine workspace member
        addFile(
            Paths.get("crates/system-manager-engine/Cargo.toml"),
            "[package]",
            "name = \"system-manager-engine\"",
            "version.workspace = true",
            "edition.workspace = true",
            "",
            "[dependencies]",
            "log.workspace = true",
            "serde.workspace = true",
            "",
            "[dev-dependencies]",
            "tokio.workspace = true",
            "",
            "[build-dependencies]",
            "cc.workspace = true"
        );

        // Cargo.lock
        addFile(
            Paths.get("Cargo.lock"),
            "# This file is automatically @generated by Cargo.",
            "# It is not intended for manual editing.",
            "version = 4",
            "",
            "[[package]]",
            "name = \"system-manager\"",
            "version = \"1.0.0\"",
            "dependencies = [",
            " \"anyhow\",",
            " \"clap\",",
            " \"system-manager-engine\",",
            "]",
            "",
            "[[package]]",
            "name = \"system-manager-engine\"",
            "version = \"1.0.0\"",
            "dependencies = [",
            " \"cc\",",
            " \"log\",",
            " \"serde\",",
            " \"tokio\",",
            "]",
            "",
            "[[package]]",
            "name = \"anyhow\"",
            "version = \"1.0.68\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "",
            "[[package]]",
            "name = \"clap\"",
            "version = \"4.1.4\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "dependencies = [",
            " \"clap_builder\",",
            " \"clap_derive\",",
            "]",
            "",
            "[[package]]",
            "name = \"clap_builder\"",
            "version = \"4.1.4\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "dependencies = [",
            " \"anstyle\",",
            "]",
            "",
            "[[package]]",
            "name = \"clap_derive\"",
            "version = \"4.1.4\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "",
            "[[package]]",
            "name = \"anstyle\"",
            "version = \"1.0.13\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "",
            "[[package]]",
            "name = \"log\"",
            "version = \"0.4.17\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "",
            "[[package]]",
            "name = \"serde\"",
            "version = \"1.0.152\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "dependencies = [",
            " \"serde_derive\",",
            "]",
            "",
            "[[package]]",
            "name = \"serde_derive\"",
            "version = \"1.0.152\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "",
            "[[package]]",
            "name = \"tokio\"",
            "version = \"1.35.0\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "dependencies = [",
            " \"pin-project-lite\",",
            "]",
            "",
            "[[package]]",
            "name = \"pin-project-lite\"",
            "version = \"0.2.13\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            "",
            "[[package]]",
            "name = \"cc\"",
            "version = \"1.0.79\"",
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"",
            ""
        );
    }

    @NotNull
    @Override
    public Detectable create(@NotNull DetectableEnvironment detectableEnvironment) {
        return detectableFactory.createCargoLockfileDetectable(
            detectableEnvironment,
            new CargoDetectableOptions(EnumListFilter.excludeNone())
        );
    }

    @Override
    public void assertExtraction(@NotNull Extraction extraction) {
        Assertions.assertEquals(2, extraction.getCodeLocations().size());

        NameVersionGraphAssert graphAssert = new NameVersionGraphAssert(Forge.CRATES, extraction.getCodeLocations().get(0).getDependencyGraph());

        // Verify workspace members
        graphAssert.hasRootDependency("clap", "4.1.4");
        graphAssert.hasRootDependency("anyhow", "1.0.68");

        // Verify transitive dependencies from clap
        graphAssert.hasParentChildRelationship("clap", "4.1.4", "clap_builder", "4.1.4");
        graphAssert.hasParentChildRelationship("clap", "4.1.4", "clap_derive", "4.1.4");
        graphAssert.hasParentChildRelationship("clap_builder", "4.1.4", "anstyle", "1.0.13");

        graphAssert.hasRootSize(2);
    }
}